apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: medusa
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: undercry927/medusa-web:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
