apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-pg-config
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres-service.medusa.svc.cluster.local
  POSTGRES_PORT: "55432"
