apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pg-pvc
  namespace: medusa
  labels:
    app: backup-pg
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
