apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-pg-cronjob
spec:
  schedule: "0 * * * *" # Toutes les heures
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-pg
              image: undercry927/medusa-backup-pg:latest
              imagePullPolicy: Always
              volumeMounts:
                - name: backup-pg-storage
                  mountPath: /backups
              envFrom:
                - configMapRef:
                    name: backup-pg-config
          restartPolicy: Never
          volumes:
            - name: backup-pg-storage
              persistentVolumeClaim:
                claimName: backup-pg-pvc
